/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.93
 * Generated at: 2023-10-26 08:40:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;

public final class yy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1698110680986L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Base Styles */\r\n");
      out.write("\r\n");
      out.write("        :root {\r\n");
      out.write("            font-size: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        *,\r\n");
      out.write("        *::before,\r\n");
      out.write("        *::after {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: \"Open Sans\", Arial, sans-serif;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background-color: #fafafa;\r\n");
      out.write("            color: #262626;\r\n");
      out.write("            padding-bottom: 3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        img {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 93.5rem;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font: inherit;\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: inherit;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:focus {\r\n");
      out.write("            outline: 0.5rem auto #4d90fe;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .visually-hidden {\r\n");
      out.write("            position: absolute !important;\r\n");
      out.write("            height: 1px;\r\n");
      out.write("            width: 1px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            clip: rect(1px, 1px, 1px, 1px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Profile Section */\r\n");
      out.write("\r\n");
      out.write("        .profile {\r\n");
      out.write("            padding: 5rem 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile::after {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            display: block;\r\n");
      out.write("            clear: both;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-image {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: calc(33.333% - 1rem);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-right: 3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-image img {\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-user-settings,\r\n");
      out.write("        .profile-stats,\r\n");
      out.write("        .profile-bio {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: calc(66.666% - 2rem);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-user-settings {\r\n");
      out.write("            margin-top: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-user-name {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 3.2rem;\r\n");
      out.write("            font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-edit-btn {\r\n");
      out.write("            font-size: 1.4rem;\r\n");
      out.write("            line-height: 1.8;\r\n");
      out.write("            border: 0.1rem solid #dbdbdb;\r\n");
      out.write("            border-radius: 0.3rem;\r\n");
      out.write("            padding: 0 2.4rem;\r\n");
      out.write("            margin-left: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-settings-btn {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            margin-left: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-stats {\r\n");
      out.write("            margin-top: 2.3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-stats li {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 1.6rem;\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("            margin-right: 4rem;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-stats li:last-of-type {\r\n");
      out.write("            margin-right: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-bio {\r\n");
      out.write("            font-size: 1.6rem;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("            margin-top: 2.3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-stat-count,\r\n");
      out.write("        .profile-edit-btn {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Gallery Section */\r\n");
      out.write("\r\n");
      out.write("        .gallery {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            margin: -1rem -1rem;\r\n");
      out.write("            padding-bottom: 3rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-item {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            flex: 1 0 22rem;\r\n");
      out.write("            margin: 1rem;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .gallery-item img {\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            max-width: 250px;\r\n");
      out.write("            max-height: 300px;\r\n");
      out.write("            min-height: 250px;\r\n");
      out.write("        }\r\n");
      out.write("        .gallery-item:hover .gallery-item-info,\r\n");
      out.write("        .gallery-item:focus .gallery-item-info {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.3);\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            max-width: 250px;\r\n");
      out.write("            max-height: 300px;\r\n");
      out.write("            min-height: 250px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-item-info {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-item-info li {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 1.7rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-item-likes {\r\n");
      out.write("            margin-right: 2.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-item-type {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 1rem;\r\n");
      out.write("            right: 1rem;\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            text-shadow: 0.2rem 0.2rem 0.2rem rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .fa-clone,\r\n");
      out.write("        .fa-comment {\r\n");
      out.write("            transform: rotateY(180deg);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-image {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Loader */\r\n");
      out.write("\r\n");
      out.write("        .loader {\r\n");
      out.write("            width: 5rem;\r\n");
      out.write("            height: 5rem;\r\n");
      out.write("            border: 0.6rem solid #999;\r\n");
      out.write("            border-bottom-color: transparent;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            animation: loader 500ms linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Media Query */\r\n");
      out.write("\r\n");
      out.write("        @media screen and (max-width: 40rem) {\r\n");
      out.write("            .profile {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                flex-wrap: wrap;\r\n");
      out.write("                padding: 4rem 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile::after {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-image,\r\n");
      out.write("            .profile-user-settings,\r\n");
      out.write("            .profile-bio,\r\n");
      out.write("            .profile-stats {\r\n");
      out.write("                float: none;\r\n");
      out.write("                width: auto;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-image img {\r\n");
      out.write("                width: 7.7rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-user-settings {\r\n");
      out.write("                flex-basis: calc(100% - 10.7rem);\r\n");
      out.write("                display: flex;\r\n");
      out.write("                flex-wrap: wrap;\r\n");
      out.write("                margin-top: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-user-name {\r\n");
      out.write("                font-size: 2.2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-edit-btn {\r\n");
      out.write("                order: 1;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-top: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-edit-btn {\r\n");
      out.write("                margin-left: 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-bio {\r\n");
      out.write("                font-size: 1.4rem;\r\n");
      out.write("                margin-top: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-edit-btn,\r\n");
      out.write("            .profile-bio,\r\n");
      out.write("            .profile-stats {\r\n");
      out.write("                flex-basis: 100%;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-stats {\r\n");
      out.write("                order: 1;\r\n");
      out.write("                margin-top: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-stats ul {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                padding: 1.2rem 0;\r\n");
      out.write("                border-top: 0.1rem solid #dadada;\r\n");
      out.write("                border-bottom: 0.1rem solid #dadada;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-stats li {\r\n");
      out.write("                font-size: 1.4rem;\r\n");
      out.write("                flex: 1;\r\n");
      out.write("                margin: 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-stat-count {\r\n");
      out.write("                display: block;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Spinner Animation */\r\n");
      out.write("\r\n");
      out.write("        @keyframes loader {\r\n");
      out.write("            to {\r\n");
      out.write("                transform: rotate(360deg);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /*\r\n");
      out.write("\r\n");
      out.write("        The following code will only run if your browser supports CSS grid.\r\n");
      out.write("\r\n");
      out.write("        Remove or comment-out the code block below to see how the browser will fall-back to flexbox & floated styling. \r\n");
      out.write("\r\n");
      out.write("        */\r\n");
      out.write("\r\n");
      out.write("        @supports (display: grid) {\r\n");
      out.write("            .profile {\r\n");
      out.write("                display: grid;\r\n");
      out.write("                grid-template-columns: 1fr 2fr;\r\n");
      out.write("                grid-template-rows: repeat(3, auto);\r\n");
      out.write("                grid-column-gap: 3rem;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-image {\r\n");
      out.write("                grid-row: 1 / -1;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .gallery {\r\n");
      out.write("                display: grid;\r\n");
      out.write("                grid-template-columns: repeat(auto-fit, minmax(22rem, 1fr));\r\n");
      out.write("                grid-gap: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .profile-image,\r\n");
      out.write("            .profile-user-settings,\r\n");
      out.write("            .profile-stats,\r\n");
      out.write("            .profile-bio,\r\n");
      out.write("            .gallery-item,\r\n");
      out.write("            .gallery {\r\n");
      out.write("                width: auto;\r\n");
      out.write("                margin: 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @media (max-width: 40rem) {\r\n");
      out.write("                .profile {\r\n");
      out.write("                    grid-template-columns: auto 1fr;\r\n");
      out.write("                    grid-row-gap: 1.5rem;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .profile-image {\r\n");
      out.write("                    grid-row: 1 / 2;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .profile-user-settings {\r\n");
      out.write("                    display: grid;\r\n");
      out.write("                    grid-template-columns: auto 1fr;\r\n");
      out.write("                    grid-gap: 1rem;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .profile-edit-btn,\r\n");
      out.write("                .profile-stats,\r\n");
      out.write("                .profile-bio {\r\n");
      out.write("                    grid-column: 1 / -1;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .profile-user-settings,\r\n");
      out.write("                .profile-edit-btn,\r\n");
      out.write("                .profile-settings-btn,\r\n");
      out.write("                .profile-bio,\r\n");
      out.write("                .profile-stats {\r\n");
      out.write("                    margin: 0;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #follow-btn{\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .textBox{\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            background-color: rgb(228, 228, 228);\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            max-width: 250px;\r\n");
      out.write("            max-height: 300px;\r\n");
      out.write("            min-height: 250px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .textBox-btn{\r\n");
      out.write("            width: 25px;\r\n");
      out.write("            height: 25px;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-user-settings{\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .profile-settings-btn{\r\n");
      out.write("             \r\n");
      out.write("           \r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- jquery 3.7.1 -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\r\n");
      out.write("    integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');

	String contextPath = request.getContextPath();
	
	Member loginUser = (Member)session.getAttribute("loginUser");   
	// 로그인 시도 전 menuber.jsp로딩시 해당객체 : null
	// 로그인 성공 후 menuber.jsp로딩시 해당객체 : 로그인 성공한 회원의 정보
	
	String alertMsg = (String)session.getAttribute("alertMsg"); 
	// 서비스 요청 전 menuber.jsp로딩시 : null
	// 서비스 요청 후 menuber.jsp로딩시 : alert로 띄워줄 메세지 문구

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .login-area > *{\r\n");
      out.write("      float: right;\r\n");
      out.write("    }\r\n");
      out.write("    .login-area a{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    .nav-area{background: rgb(174, 246, 248);}\r\n");
      out.write("    .menu{\r\n");
      out.write("        display: table-cell;\r\n");
      out.write("        width: 150px;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    .menu a{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: rgb(0, 0, 0);\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        display: block;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        line-height: 50px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write(" <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- jquery 3.7.1 -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\r\n");
      out.write("    integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
 if(alertMsg != null) { 
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			alert(\"");
      out.print(alertMsg);
      out.write("\");\r\n");
      out.write("		</script>\r\n");
      out.write("		");
 session.removeAttribute("alertMsg"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <h1 align=\"center\">Welcome GIMAN World</h1>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"login-area\">\r\n");
      out.write("        ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("            <!-- case1. 로그인 전 -->\r\n");
      out.write("            <form action=\"");
      out.print(contextPath );
      out.write("/login.me\" method=\"POST\">\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>아이디</th>\r\n");
      out.write("                        <td><input type=\"text\" name=\"userId\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>비밀번호</th>\r\n");
      out.write("                        <td><input type=\"password\" name=\"userPwd\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th colspan=\"2\">\r\n");
      out.write("                            <button type=\"submit\">로그인</button>\r\n");
      out.write("                            <button type=\"button\" onclick=\"enrollPage();\">회원가입</button>\r\n");
      out.write("                        </th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                <script>\r\n");
      out.write("                	// 회원가입 페이지를 요청\r\n");
      out.write("                	function enrollPage(){\r\n");
      out.write("                		//location.href = \"");
      out.print(contextPath );
      out.write("/views/member/memberEnrollForm.jsp\";\r\n");
      out.write("                		// 웹 애플리케이션의 디렉토리 구조가 url에 노출되면 보안에 취약\r\n");
      out.write("                		\r\n");
      out.write("                		// 단순한 페이지 요청도 servlet호출해서 servlet거쳐갈 것(즉, url에는 서블릿 맵핑값만 나타나도록)\r\n");
      out.write("                		location.href = \"");
      out.print(contextPath);
      out.write("/enrollForm.me\";\r\n");
      out.write("                	}\r\n");
      out.write("                </script>\r\n");
      out.write("            </form>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <!-- case2. 로그인 후 -->\r\n");
      out.write("            <div>\r\n");
      out.write("                <b>");
      out.print(loginUser.getUserName() );
      out.write("님</b>의 방문을 환영합니다. <br><br>\r\n");
      out.write("                <div align=\"center\">\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/myPage.me\">마이페이지</a>\r\n");
      out.write("                    <a href=\"");
      out.print(contextPath );
      out.write("/logout.me\">로그아웃</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"nav-area\" align=\"center\">\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print(contextPath);
      out.write("\">HOME</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print(contextPath);
      out.write("/list.no\">공지사항</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print(contextPath);
      out.write("/list.bo?cpage=1\">일반게시판</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print(contextPath);
      out.write("/list.th\">사진게시판</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("    \r\n");
      out.write("            <div class=\"profile\">\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"profile-image\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1513721032312-6a18a42c8763?w=152&h=152&fit=crop&crop=faces\" alt=\"\">\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"profile-user-settings\">\r\n");
      out.write("                    \r\n");
      out.write("                    <h1 class=\"profile-user-name\">userName</h1>\r\n");
      out.write("    \r\n");
      out.write("                    <button class=\"btn profile-edit-btn, btn btn-info\" id=\"follow-btn\">íë¡ì° ìì²­</button>\r\n");
      out.write("    \r\n");
      out.write("                    <button class=\"btn profile-settings-btn\" style=\"position: absolute;\r\n");
      out.write("                    right: 0;\r\n");
      out.write("                    padding: 0;\r\n");
      out.write("                    margin: 0;\r\n");
      out.write("                    border: none;\r\n");
      out.write("                    top: -20px;\r\n");
      out.write("                    width: 20px;\r\n");
      out.write("                    height: 20px;\"  aria-label=\"profile settings\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" fill=\"currentColor\" class=\"bi bi-gear\" viewBox=\"0 0 16 16\"\r\n");
      out.write("                    >\r\n");
      out.write("                      <path d=\"M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z\"></path>\r\n");
      out.write("                      <path d=\"M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z\"></path>\r\n");
      out.write("                    </svg></button>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"profile-stats\">\r\n");
      out.write("    \r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><span class=\"profile-stat-count\">188</span> íë¡ì</li>\r\n");
      out.write("                        <li><span class=\"profile-stat-count\">206</span> íë¡ì</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"profile-bio\">\r\n");
      out.write("    \r\n");
      out.write("                    <p> ìíë©ì¸ì§ ê³µê°ìëë¤. </p>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End of profile section -->\r\n");
      out.write("    \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of container -->\r\n");
      out.write("    \r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <main>\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("    \r\n");
      out.write("            <div class=\"gallery \">\r\n");
      out.write("                <div class=\"textBox gallery-item\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"35\" height=\"35\" fill=\"currentColor\" class=\"bi bi-plus-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                            <path d=\"M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z\"/>\r\n");
      out.write("                            <path d=\"M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z\"/>\r\n");
      out.write("                          </svg>\r\n");
      out.write("                          <div class=\"gallery-item-info\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1511765224389-37f0e77cf0eb?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1497445462247-4330a224fdb1?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-type\">\r\n");
      out.write("    \r\n");
      out.write("                        <span class=\"visually-hidden\">Gallery</span><i class=\"fas fa-clone\" aria-hidden=\"true\"></i>\r\n");
      out.write("    \r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">    \r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1502630859934-b3b41d18206c?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-type\">\r\n");
      out.write("    \r\n");
      out.write("                        <span class=\"visually-hidden\">Video</span><i class=\"fas fa-video\" aria-hidden=\"true\"></i>\r\n");
      out.write("    \r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1498471731312-b6d2b8280c61?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-type\">\r\n");
      out.write("    \r\n");
      out.write("                        <span class=\"visually-hidden\">Gallery</span><i class=\"fas fa-clone\" aria-hidden=\"true\"></i>\r\n");
      out.write("    \r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1515023115689-589c33041d3c?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1515814472071-4d632dbc5d4a?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1511407397940-d57f68e81203?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1518481612222-68bbe828ecd1?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1505058707965-09a4469a87e4?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"gallery-item\" tabindex=\"0\">\r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1423012373122-fff0a5d28cc9?w=500&h=500&fit=crop\" class=\"gallery-image\" alt=\"\">\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"gallery-item-info\">\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End of gallery -->\r\n");
      out.write("    \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of container -->\r\n");
      out.write("    \r\n");
      out.write("    </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
