/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.93
 * Generated at: 2023-10-26 03:21:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>* EL(Expression Language) 표현언어</h1>\r\n");
      out.write("	<p>\r\n");
      out.write("		기존에 사용했던 표현식(출력식) &lt;= name =&gt;와 같이 <br>\r\n");
      out.write("		JSP상에서 표현하고자하는 값을 ${name}의 형식으로 표현해서 작성하는 것\r\n");
      out.write("	</p>\r\n");
      out.write("	\r\n");
      out.write("	<h4><a href=\"el.do\">01_EL의 기본구문</a></h4>\r\n");
      out.write("	<h4><a href=\"operation.do\">02_EL의 연산자</a></h4>\r\n");
      out.write("	<br>\r\n");
      out.write("	<!-- \r\n");
      out.write("		*JSP를 이루는 구성인자\r\n");
      out.write("		1.스크립팅 원소 : JSP페이지에서 자바코드를 직접 기술할 수 있게 하는 기능\r\n");
      out.write("					ex) 스크립틀릿, 표현식(출력식) 등등...\r\n");
      out.write("		2. 지시어 : JSP페이지정보에 대한 내용을 표현한다거나 또 다른 페이지를 포함할 때 사용\r\n");
      out.write("				  JSP 기능을 확장시키는 라이브러리 등록할떄도 사용한다.\r\n");
      out.write("				  ex) page지시어, include지시어, taglib지시어\r\n");
      out.write("		3. 액션태그(표준액션태그, 커스텀액션태그) : xml기술을 이용해서 기존의 jsp문법을 확장하는 기술을 제공하는 태그\r\n");
      out.write("	 	\r\n");
      out.write("	 		>> 표준액션태그  : JSP페이지에서 바로 사용가능(별도의 변동이 필요하지 않다.)\r\n");
      out.write("	 					  모든 태그명 앞에 jsp: 접두어를 붙임\r\n");
      out.write("	 		\r\n");
      out.write("	 		>> 커스텀액션태그 : JSP페이지에서 바로 사용 불가능(별도의 라이브러리 연동 필요)\r\n");
      out.write("	 					   모든 태그명 앞에 jsp:외의 다른 접두어를 붙임(종류가 다양)\r\n");
      out.write("	 					   가장 대표적으로 유용한 라이브러리는 == JSTL\r\n");
      out.write("	 -->\r\n");
      out.write("	<h1>JSP Action Tag</h1>\r\n");
      out.write("	<p>XML기술을 이용해서 기존의 JSP문법을 확장시키는 기술을 제공하는 태그들</p>\r\n");
      out.write("	<h3>1. 표준액션태그</h3>\r\n");
      out.write("	<a href=\"views/2_standardAction/01_include.jsp\">01_jsp:include</a>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
